language: c
compiler: gcc
before_install: sudo apt-get install libgsl-dev
script:
  - cd src
  - make clean
  - make all
  - ./watts_strogatz.exe 1000 10 0.1

notifications:
  email:
    - willprobert@gmail.com
